# Generated by Django 2.1.7 on 2019-03-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lan', '0001_initial'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='relevant_to',
            field=models.ManyToManyField(blank=True, to='lan.LAN'),
        ),
    ]
