# Generated by Django 2.2.2 on 2019-06-23 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('banner_url', models.CharField(blank=True, max_length=100, verbose_name='banner')),
                ('logo_url', models.URLField(blank=True, max_length=100, verbose_name='logo')),
                ('website', models.URLField(blank=True, verbose_name='website')),
            ],
        ),
        migrations.CreateModel(
            name='SponsorRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=10, verbose_name='priority')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsor.Sponsor')),
            ],
            options={
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='events',
            field=models.ManyToManyField(related_name='sponsors', through='sponsor.SponsorRelation', to='event.Event'),
        ),
    ]
