# Generated by Django 2.2.2 on 2019-06-10 14:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nick', models.CharField(db_index=True, help_text='Specify a nick name (display name).', max_length=20, verbose_name='nick')),
                ('date_of_birth', models.DateField(default=datetime.date.today, verbose_name='Date of birth')),
                ('address', models.CharField(max_length=100, verbose_name='Street address')),
                ('zip_code', models.CharField(max_length=4, verbose_name='Zip code')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
