# Generated by Django 2.2.2 on 2019-07-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seating', '0001_initial'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='assigned_ticket',
            field=models.OneToOneField(blank=True, help_text='Ticket assigned to this seat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat', to='ticket.Ticket', verbose_name='assigned ticket'),
        ),
        migrations.AddField(
            model_name='seat',
            name='seating',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='seating.Seating', verbose_name='seating'),
        ),
        migrations.AddField(
            model_name='rowtickettype',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_ticket_types', to='seating.Area', verbose_name='area'),
        ),
        migrations.AddField(
            model_name='rowtickettype',
            name='ticket_type',
            field=models.ForeignKey(help_text='A ticket type available for this seating row.', on_delete=django.db.models.deletion.CASCADE, related_name='applicable_rows', to='ticket.TicketType', verbose_name='ticket types'),
        ),
        migrations.AddField(
            model_name='rowlayout',
            name='area_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_layouts', to='seating.AreaLayout', verbose_name='area layout'),
        ),
        migrations.AddField(
            model_name='area',
            name='area_layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='seating.AreaLayout', verbose_name='area layout'),
        ),
        migrations.AddField(
            model_name='area',
            name='seating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='seating.Seating', verbose_name='seating'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('area', 'row_number', 'seat_number'), name='unique_area_row_seat'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(check=models.Q(row_number__gte=1), name='row_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.CheckConstraint(check=models.Q(seat_number__gte=1), name='seat_number_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='rowtickettype',
            constraint=models.UniqueConstraint(fields=('area', 'row_number', 'ticket_type'), name='unique_area_row_ticket_type'),
        ),
        migrations.AddIndex(
            model_name='rowlayout',
            index=models.Index(fields=['area_layout', 'row_number'], name='seating_row_area_la_a1d5e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='rowlayout',
            constraint=models.UniqueConstraint(fields=('area_layout', 'row_number'), name='unique_layout_area_row_number'),
        ),
        migrations.AddConstraint(
            model_name='rowlayout',
            constraint=models.CheckConstraint(check=models.Q(row_number__gte=1), name='row_number_gte_1'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['seating', 'area_code'], name='seating_are_seating_a1433a_idx'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('seating', 'area_code'), name='unique_area_code'),
        ),
    ]
