# Generated by Django 2.2.2 on 2019-06-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rowlayout',
            name='description',
            field=models.CharField(blank=True, help_text='A short description for users. May be used as row name.', max_length=50, verbose_name='description'),
        ),
    ]
