# Generated by Django 2.2.2 on 2019-06-25 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arealayout',
            name='long_title',
            field=models.CharField(help_text='A long, unique title to show behind the scenes.', max_length=50, unique=True, verbose_name='long title'),
        ),
        migrations.AlterField(
            model_name='rowlayout',
            name='row_number',
            field=models.IntegerField(help_text='Unique, positive row number within the area.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='row number'),
        ),
    ]
