# Generated by Django 2.2.2 on 2019-06-28 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seating', '0002_rowlayout_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rowlayout',
            name='offset_horizontal',
            field=models.FloatField(default=0, help_text='Offset in meters from the left wrt. the area.', verbose_name='horizontal offset'),
        ),
        migrations.AlterField(
            model_name='rowlayout',
            name='offset_vertical',
            field=models.FloatField(default=0, help_text='Offset in meters from the top wrt. the area.', verbose_name='vertical offset'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(help_text='Seat number in the row. Horizontal-major numbering.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='seat number'),
        ),
    ]
