# Generated by Django 2.2.2 on 2019-06-24 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(help_text='A short, non-unique title to show to users.', max_length=20, verbose_name='short title')),
                ('long_title', models.CharField(help_text='A longer, unique title.', max_length=50, unique=True, verbose_name='long title')),
                ('priority', models.IntegerField(default=10, help_text='Lower priority shows it higher on the list among other ticket types.', verbose_name='priority')),
                ('event', models.ForeignKey(help_text='Which event this is for.', on_delete=django.db.models.deletion.PROTECT, related_name='ticket_types', to='event.Event', verbose_name='event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(editable=False, help_text='When it was bought.', verbose_name='purchase date')),
                ('owner', models.ForeignKey(editable=False, help_text='The user owning the ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('ticket_type', models.ForeignKey(editable=False, help_text='Ticket type.', on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='ticket.TicketType', verbose_name='type')),
            ],
        ),
    ]
