# Generated by Django 2.2.2 on 2019-07-01 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='priority',
            field=models.IntegerField(default=10, help_text='Lower priority shows it higher on the list among other ticket types.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='priority'),
        ),
    ]
